import { practiceProductSchema, shoppingMissionSchema } from "@/lib/shopping/schemas";
import { z } from "zod";

const cableImage = {
  src: "/images/shopping/products/digital/usb-c-cable-white-2m.jpg",
  alt: "흰색 USB C타입 충전 케이블 연습용 예시 사진",
  width: 800,
  height: 800,
  kind: "product-photoreal" as const,
  background: "white" as const,
  angle: "three-quarter" as const,
  generationPromptId: "product-digital-usb-c-white",
};

const rainyHero = {
  src: "/images/shopping/missions/rainy-season-budget.jpg",
  alt: "현관에 우산, 제습제, 미끄럼방지 테이프와 방수 신발 덮개를 정돈한 장마철 준비 장면",
  width: 1200,
  height: 900,
  kind: "mission-lifestyle" as const,
  background: "lifestyle" as const,
  generationPromptId: "mission-rainy-season-entryway",
};

export const SHOPPING_PRODUCTS = z.array(practiceProductSchema).parse([
  {
    id: "cable-usbc-white-2m",
    categoryId: "charging-cable",
    title: "C타입 고속 충전 케이블 2m",
    shortLabel: "흰색 C타입 케이블",
    description: "C타입 단자 두 개가 달린 2m 길이의 연습용 케이블입니다.",
    examplePrice: 6900,
    shippingFee: 0,
    bundleQuantity: 1,
    image: cableImage,
    features: { 단자: "C타입-C타입", 길이: "2m", 색상: "화이트", 구성: "1개" },
    badges: ["무료배송"],
    isPracticeOnly: true,
    disclosure: "연습용 예시 상품",
  },
  {
    id: "cable-usbc-black-1m",
    categoryId: "charging-cable",
    title: "C타입 충전 케이블 1m",
    shortLabel: "검정 C타입 케이블",
    description: "단자는 맞지만 길이가 짧고 배송비가 있는 비교용 상품입니다.",
    examplePrice: 5500,
    shippingFee: 2500,
    bundleQuantity: 1,
    image: cableImage,
    features: { 단자: "C타입-C타입", 길이: "1m", 색상: "블랙", 구성: "1개" },
    badges: [],
    isPracticeOnly: true,
    disclosure: "연습용 예시 상품",
  },
  {
    id: "cable-eightpin-white-2m",
    categoryId: "charging-cable",
    title: "8핀 충전 케이블 2m",
    shortLabel: "흰색 8핀 케이블",
    description: "길이는 맞지만 단자가 다른 상품을 구별하는 연습에 사용합니다.",
    examplePrice: 5900,
    shippingFee: 0,
    bundleQuantity: 1,
    image: cableImage,
    features: { 단자: "8핀-USB", 길이: "2m", 색상: "화이트", 구성: "1개" },
    badges: ["광고"],
    isPracticeOnly: true,
    disclosure: "연습용 예시 상품",
  },
  {
    id: "cable-usbc-white-3pack",
    categoryId: "charging-cable",
    title: "C타입 충전 케이블 3개 묶음",
    shortLabel: "C타입 케이블 묶음",
    description: "낮은 개당 가격과 실제 필요한 수량을 비교하는 연습용 상품입니다.",
    examplePrice: 10900,
    shippingFee: 0,
    bundleQuantity: 3,
    image: cableImage,
    features: { 단자: "C타입-C타입", 길이: "2m", 색상: "화이트", 구성: "3개 묶음" },
    badges: ["무료배송"],
    isPracticeOnly: true,
    disclosure: "연습용 예시 상품",
  },
  {
    id: "rain-umbrella-navy",
    categoryId: "umbrella",
    title: "접이식 자동 우산",
    shortLabel: "접이식 우산",
    description: "가방에 넣기 쉬운 장마철 필수 준비물입니다.",
    examplePrice: 12900,
    shippingFee: 0,
    bundleQuantity: 1,
    image: {
      src: "/images/shopping/products/rainy-season/compact-umbrella-navy.jpg",
      alt: "남색 접이식 우산과 우산집 연습용 예시 사진",
      width: 800,
      height: 800,
      kind: "product-photoreal",
      background: "white",
      angle: "three-quarter",
      generationPromptId: "product-rain-compact-umbrella",
    },
    features: { 종류: "접이식", 색상: "남색", 구성: "우산과 우산집" },
    badges: ["무료배송"],
    isPracticeOnly: true,
    disclosure: "연습용 예시 상품",
  },
  {
    id: "rain-dehumidifier-eight",
    categoryId: "dehumidifier",
    title: "옷장용 제습제 8개 묶음",
    shortLabel: "제습제 8개",
    description: "방과 옷장에 나누어 놓는 묶음형 제습제입니다.",
    examplePrice: 5900,
    shippingFee: 0,
    bundleQuantity: 8,
    image: {
      src: "/images/shopping/products/rainy-season/dehumidifier-box-eight-pack.jpg",
      alt: "파란 뚜껑의 제습제 8개 묶음 연습용 예시 사진",
      width: 800,
      height: 800,
      kind: "product-photoreal",
      background: "white",
      angle: "three-quarter",
      generationPromptId: "product-rain-dehumidifier-eight",
    },
    features: { 사용처: "옷장·신발장", 구성: "8개 묶음", 형태: "통형" },
    badges: [],
    isPracticeOnly: true,
    disclosure: "연습용 예시 상품",
  },
  {
    id: "rain-anti-slip-tape",
    categoryId: "anti-slip",
    title: "투명 미끄럼방지 테이프",
    shortLabel: "미끄럼방지 테이프",
    description: "젖기 쉬운 바닥에 붙이는 투명한 연습용 예시 제품입니다.",
    examplePrice: 4500,
    shippingFee: 0,
    bundleQuantity: 1,
    image: {
      src: "/images/shopping/products/rainy-season/anti-slip-tape-clear.jpg",
      alt: "표면이 오돌토돌한 투명 미끄럼방지 테이프 연습용 예시 사진",
      width: 800,
      height: 800,
      kind: "product-photoreal",
      background: "white",
      angle: "three-quarter",
      generationPromptId: "product-rain-anti-slip-tape",
    },
    features: { 색상: "투명", 형태: "롤형", 용도: "젖기 쉬운 바닥" },
    badges: [],
    isPracticeOnly: true,
    disclosure: "연습용 예시 상품",
  },
  {
    id: "rain-shoe-covers",
    categoryId: "shoe-cover",
    title: "방수 신발 덮개",
    shortLabel: "방수 신발 덮개",
    description: "비가 많이 오는 날 신발 위에 덧신는 선택 준비물입니다.",
    examplePrice: 6500,
    shippingFee: 0,
    bundleQuantity: 1,
    image: {
      src: "/images/shopping/products/rainy-season/waterproof-shoe-covers-blue.jpg",
      alt: "연한 파란색 방수 신발 덮개 한 쌍 연습용 예시 사진",
      width: 800,
      height: 800,
      kind: "product-photoreal",
      background: "white",
      angle: "three-quarter",
      generationPromptId: "product-rain-shoe-covers",
    },
    features: { 색상: "연한 파랑", 구성: "한 쌍", 용도: "비 오는 날" },
    badges: ["선택 품목"],
    isPracticeOnly: true,
    disclosure: "연습용 예시 상품",
  },
]);

export const SHOPPING_MISSIONS = z.array(shoppingMissionSchema).parse([
  {
    slug: "first-usb-c-cable",
    title: "C타입 충전 케이블 사기",
    shortTitle: "처음 쇼핑하기",
    summary: "검색부터 옵션, 장바구니와 주문 전 확인까지 순서대로 연습해요.",
    mode: "guided",
    difficulty: "처음",
    estimatedMinutes: 5,
    accent: "blue",
    visual: { cardImage: cableImage, heroImage: cableImage },
    productIds: ["cable-usbc-white-2m", "cable-usbc-black-1m", "cable-eightpin-white-2m"],
    steps: ["상품 검색", "검색 결과", "상세 정보", "옵션 선택", "장바구니", "주문 전 확인"],
    correctProductId: "cable-usbc-white-2m",
    learningPoints: ["광고 표시와 일반 상품을 구분했어요.", "단자와 길이를 먼저 확인했어요.", "수량과 배송비를 주문 전에 다시 봤어요."],
    collectionSlug: "charging",
  },
  {
    slug: "rainy-budget-30000",
    title: "3만 원으로 장마철 준비하기",
    shortTitle: "예산 장보기",
    summary: "필수 준비물을 고르고 총금액이 예산 안인지 확인해요.",
    mode: "budget",
    difficulty: "쉬움",
    estimatedMinutes: 4,
    accent: "violet",
    visual: { cardImage: rainyHero, heroImage: rainyHero },
    productIds: ["rain-umbrella-navy", "rain-dehumidifier-eight", "rain-anti-slip-tape", "rain-shoe-covers"],
    steps: ["미션 안내", "상품 고르기", "장바구니 확인", "예산 확인"],
    budget: 30000,
    requiredCategoryIds: ["umbrella", "dehumidifier", "anti-slip"],
    learningPoints: ["필수 품목과 선택 품목을 구분했어요.", "배송비를 포함한 총금액을 확인했어요.", "남은 예산을 보고 선택 품목을 결정했어요."],
    collectionSlug: "rainy-season",
  },
  {
    slug: "compare-usb-c-cables",
    title: "조건에 맞는 충전 케이블 비교하기",
    shortTitle: "상품 비교",
    summary: "가격만 보지 않고 단자, 길이, 배송비와 구성을 비교해요.",
    mode: "compare",
    difficulty: "쉬움",
    estimatedMinutes: 3,
    accent: "green",
    visual: { cardImage: cableImage, heroImage: cableImage },
    productIds: ["cable-usbc-white-2m", "cable-usbc-black-1m", "cable-usbc-white-3pack"],
    steps: ["조건 확인", "상품 비교", "선택 이유 확인"],
    correctProductId: "cable-usbc-white-2m",
    learningPoints: ["상품 가격과 배송비를 합쳐 비교했어요.", "필요한 길이와 단자를 확인했어요.", "묶음 수량이 정말 필요한지 살폈어요."],
    collectionSlug: "charging",
  },
  {
    slug: "find-order-mistake",
    title: "주문 화면의 실수 찾기",
    shortTitle: "실수 찾기",
    summary: "주문 전에 수량과 정기배송처럼 놓치기 쉬운 부분을 찾아요.",
    mode: "mistake",
    difficulty: "보통",
    estimatedMinutes: 3,
    accent: "coral",
    visual: { cardImage: cableImage, heroImage: cableImage },
    productIds: ["cable-usbc-white-2m"],
    steps: ["주문 조건", "실수 찾기", "바르게 고치기"],
    requiredMistakeIds: ["quantity", "subscription"],
    learningPoints: ["주문 수량을 다시 확인했어요.", "한 번 구매와 정기배송을 구분했어요.", "문자 링크보다 공식 주문내역을 먼저 확인하기로 했어요."],
    collectionSlug: "safe-shopping",
  },
]);

export const SHOPPING_COLLECTIONS = {
  charging: {
    slug: "charging",
    title: "충전용품 고르는 기준",
    description: "단자, 길이, 구성과 배송 조건을 다시 확인해 보세요.",
    items: [
      { id: "charging-cable", label: "C타입 충전 케이블", keyword: "C타입 충전 케이블 2m", tip: "휴대폰 단자와 필요한 길이를 먼저 확인하세요." },
      { id: "charger", label: "휴대폰 충전기", keyword: "C타입 충전기", tip: "케이블 포함 여부와 출력 규격을 확인하세요." },
    ],
  },
  "rainy-season": {
    slug: "rainy-season",
    title: "장마철 준비물 고르는 기준",
    description: "집에 이미 있는 물건을 먼저 확인하고 필요한 품목만 살펴보세요.",
    items: [
      { id: "umbrella", label: "접이식 우산", keyword: "접이식 자동 우산", tip: "무게, 접었을 때 길이와 자동 버튼 여부를 확인하세요." },
      { id: "dehumidifier", label: "옷장용 제습제", keyword: "옷장용 제습제", tip: "한 묶음의 실제 개수와 놓을 장소를 확인하세요." },
      { id: "anti-slip", label: "미끄럼방지 테이프", keyword: "욕실 미끄럼방지 테이프 투명", tip: "붙일 바닥 재질과 물에 젖는 장소인지 확인하세요." },
    ],
  },
  "safe-shopping": {
    slug: "safe-shopping",
    title: "안전한 쇼핑을 돕는 준비",
    description: "상품을 더 사기보다 주문내역과 공식 앱을 확인하는 습관부터 익혀요.",
    items: [
      { id: "magnifier", label: "휴대용 확대경", keyword: "휴대용 LED 확대경", tip: "작은 상품정보를 읽을 때 필요한 배율과 조명을 확인하세요." },
    ],
  },
} as const;

export type ShoppingCollectionSlug = keyof typeof SHOPPING_COLLECTIONS;

export function getShoppingMission(slug: string) {
  return SHOPPING_MISSIONS.find((mission) => mission.slug === slug);
}

export function getShoppingProduct(id: string) {
  return SHOPPING_PRODUCTS.find((product) => product.id === id);
}

